version: '3'

services:
  expenseTrackerDatabase:
    image: "postgres:latest"
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - expenseTracker_data:/var/lib/postgresql/data/

volumes:
  expenseTracker_data:
