version: '3'

services:
  db:
    image: "postgres:latest"
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - expenseTracker_data:/var/lib/postgresql/data/

  backend:
    build: ./expenseTrackerService
    
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  expenseTracker_data:
